import http from 'node:http';
import {readFile} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import {Store,id} from './store.js';
import {ai,AIError} from './ai.js';
import {catalog,matchScore} from './public/learning.js';
const port=Number(process.env.PORT||3040),host=process.env.HOST||(process.env.RENDER?'0.0.0.0':'127.0.0.1');
const origin=new URL(process.env.PUBLIC_ORIGIN||process.env.RENDER_EXTERNAL_URL||`http://localhost:${port}`).origin;
const allowed=new Set([origin,`http://localhost:${port}`,`http://127.0.0.1:${port}`]);
const db=new Store(process.env.DATA_FILE||fileURLToPath(new URL('./data/mindmate.json',import.meta.url)));
const files={'/':'index.html','/app.js':'app.js','/engine.js':'engine.js','/learning.js':'learning.js','/styles.css':'styles.css','/favicon.svg':'favicon.svg'};
const limits=new Map();
function checkLimit(who,kind,max){const key=who+kind,now=Date.now();let l=limits.get(key);if(!l||now-l.start>60000){l={start:now,n:0};limits.set(key,l);}if(++l.n>max)throw new AIError('Too many requests. Please wait a minute.',429);if(limits.size>2000)for(const [k,v]of limits)if(now-v.start>60000)limits.delete(k);}
function text(v,max=200){if(typeof v!=='string'||!v.trim()||v.length>max)throw new AIError('Please check the required fields and their length.',400);return v.trim();}
function ownRoom(room,user){if(!room)throw new AIError('Room not found.',404);if(!room.members.includes(user.id))throw new AIError('Join this room with an invitation first.',403);}
function timer(room){const t=room.timer;if(!t.running)return {...t};const cycle=1800000,elapsed=Math.max(0,Date.now()-t.started),offset=elapsed%cycle;return {...t,phase:offset<1500000?'Focus':'Break',remaining:Math.ceil(((offset<1500000?1500000:cycle)-offset)/1000),cycles:Math.floor(elapsed/cycle)};}
function roomView(r,u){const q=r.quiz;return {...r,invite:undefined,members:r.members.map(uid=>({id:uid,name:db.data.users[uid]?.profile?.name||'Learner',online:Date.now()-(r.seen?.[uid]||0)<15000})),timer:timer(r),quiz:q?{id:q.id,question:q.question,options:q.options,topic:q.topic,closed:q.closed,answered:!!q.answers[u.id],yourAnswer:q.answers[u.id],explanation:q.closed?q.explanation:undefined,correct:q.closed?q.correct:undefined,answeredCount:Object.keys(q.answers).length}:null,leaderboard:r.quiz&&!r.quiz.closed?[]:Object.entries(r.scores||{}).map(([uid,s])=>({name:db.data.users[uid]?.profile?.name||'Learner',...s})).sort((a,b)=>b.points-a.points),scores:undefined,serverNow:Date.now()};}
export const server=http.createServer(async(req,res)=>{
 const json=(code,value)=>{res.writeHead(code,{'Content-Type':'application/json; charset=utf-8'});res.end(JSON.stringify(value));};
 res.setHeader('Cache-Control','no-store');res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Referrer-Policy','no-referrer');res.setHeader('Content-Security-Policy',"default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob:; connect-src 'self'; frame-ancestors 'none'; base-uri 'none'; form-action 'self'");
 try{
 if(![...allowed].some(o=>new URL(o).host===req.headers.host))throw new AIError('Host not allowed. Configure PUBLIC_ORIGIN for your deployment.',403);
 const url=new URL(req.url,origin),path=url.pathname;
 if(req.method==='GET'&&!path.startsWith('/api/')){const file=files[path]||(path.startsWith('/room/')?'index.html':null);if(!file)return json(404,{error:'Not found.'});const body=await readFile(new URL('./public/'+file,import.meta.url));res.writeHead(200,{'Content-Type':file.endsWith('.js')?'text/javascript; charset=utf-8':file.endsWith('.css')?'text/css; charset=utf-8':file.endsWith('.svg')?'image/svg+xml':'text/html; charset=utf-8'});return res.end(body);}
 if(req.headers.origin&&!allowed.has(req.headers.origin))throw new AIError('Origin not allowed.',403);
 if(req.method==='GET'&&path==='/api/config')return json(200,{live:!!process.env.OPENAI_API_KEY,origin,local:host==='127.0.0.1'});
 let body={};if(req.method==='POST'){if(!req.headers['content-type']?.startsWith('application/json'))throw new AIError('JSON required.',415);let raw='',bytes=0;for await(const chunk of req){bytes+=chunk.length;if(bytes>4500000)throw new AIError('Request is too large.',413);raw+=chunk;}try{body=JSON.parse(raw);}catch{throw new AIError('Invalid JSON.',400);}}
 const token=(req.headers.cookie||'').split(';').map(s=>s.trim()).find(s=>s.startsWith('mm_session='))?.slice(11);let user=db.authenticate(token);
 if(req.method==='POST'&&path==='/api/session'){if(!user){checkLimit(req.socket.remoteAddress,'signup',12);const created=db.createUser();user=created.user;res.setHeader('Set-Cookie',`mm_session=${created.token}; HttpOnly; SameSite=Strict; Path=/; Max-Age=2592000${origin.startsWith('https:')?'; Secure':''}`);}return json(200,{id:user.id,profile:user.profile,invitations:user.invitations});}
 if(!user)throw new AIError('Your local session expired. Refresh the page.',401);
 checkLimit(user.id,'requests',250);
 if(path==='/api/profile'&&req.method==='POST'){
 const p=body;const profile={name:text(p.name,40),subject:text(p.subject,60),topic:text(p.topic,80),course:text(p.course,80),goal:text(p.goal,100),level:text(p.level,20),preference:text(p.preference,20),timezone:text(p.timezone,60),start:text(p.start,5),end:text(p.end,5),days:p.days,discoverable:p.discoverable===true};
 if(!['Beginner','Intermediate','Advanced'].includes(p.level)||!['Online','In person','Either'].includes(p.preference)||!/^([01]\d|2[0-3]):[0-5]\d$/.test(p.start)||!/^([01]\d|2[0-3]):[0-5]\d$/.test(p.end)||p.start>=p.end||!Array.isArray(p.days)||!p.days.length||p.days.some(d=>!['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].includes(d)))throw new AIError('Choose valid availability, level and meeting preference. End time must follow start time.',400);
 user.profile=profile;db.save();return json(200,{profile});}
 if(path==='/api/buddies'&&req.method==='GET'){if(!user.profile)return json(200,{buddies:[],invitations:user.invitations});const q=(url.searchParams.get('q')||'').toLowerCase();return json(200,{buddies:Object.values(db.data.users).filter(u=>u.id!==user.id&&u.profile?.discoverable&&JSON.stringify(u.profile).toLowerCase().includes(q)).map(u=>({id:u.id,...u.profile,...matchScore(user.profile,u.profile)})).sort((a,b)=>b.score-a.score).slice(0,50),invitations:user.invitations});}
 if(path==='/api/rooms'&&req.method==='GET')return json(200,{rooms:user.rooms.map(rid=>db.data.rooms[rid]).filter(Boolean).map(r=>({id:r.id,name:r.name,topic:r.topic,goal:r.goal,members:r.members.length}))});
 if(path==='/api/rooms'&&req.method==='POST'){checkLimit(user.id,'createRoom',10);const rid=id();const room={id:rid,invite:id(),owner:user.id,name:text(body.name,80),topic:text(body.topic,100),goal:text(body.goal,200),target:Math.max(1,Math.min(1000,Number(body.target)||1)),completed:0,members:[user.id],seen:{},messages:[],notes:'',notesVersion:0,timer:{running:false,remaining:1500,phase:'Focus'},quiz:null,quizIndex:0,scores:{}};db.data.rooms[rid]=room;user.rooms.push(rid);db.save();return json(201,{room:roomView(room,user),link:`${origin}/room/${rid}#invite=${room.invite}`});}
 if(path==='/api/join'&&req.method==='POST'){const r=db.data.rooms[body.room];if(!r||r.invite!==body.invite)throw new AIError('This invitation is invalid or was rotated.',403);if(r.members.length>=30&&!r.members.includes(user.id))throw new AIError('This room is full.',409);if(!r.members.includes(user.id))r.members.push(user.id);if(!user.rooms.includes(r.id))user.rooms.push(r.id);db.save();return json(200,{room:roomView(r,user)});}
 const match=path.match(/^\/api\/rooms\/([\w-]+)(?:\/(\w+))?$/);
 if(match){const r=db.data.rooms[match[1]],action=match[2];ownRoom(r,user);if(req.method==='GET'){r.seen[user.id]=Date.now();return json(200,{room:roomView(r,user)});}if(req.method!=='POST')throw new AIError('Method not allowed.',405);
 if(action==='message'){r.messages.push({id:id(),user:user.id,name:user.profile?.name||'Learner',text:text(body.text,3000),at:Date.now()});r.messages=r.messages.slice(-150);}
 else if(action==='notes'){if(body.version!==r.notesVersion)throw new AIError('Notes changed in another browser. Your draft is preserved; reload the latest notes before merging.',409);if(typeof body.notes!=='string'||body.notes.length>20000)throw new AIError('Notes must be under 20,000 characters.',400);r.notes=body.notes;r.notesVersion++;}
 else if(action==='invite'){if(user.id!==r.owner)throw new AIError('Only the room owner can send invitations.',403);const target=db.data.users[body.userId];if(!target?.profile?.discoverable)throw new AIError('That learner is not available for invitations.',404);if(!target.invitations.some(i=>i.room===r.id))target.invitations.push({room:r.id,name:r.name,from:user.profile?.name||'Learner',invite:r.invite});}
 else if(action==='link'){return json(200,{link:`${origin}/room/${r.id}#invite=${r.invite}`});}
 else if(action==='timer'){if(user.id!==r.owner)throw new AIError('The room owner controls the shared timer.',403);const t=timer(r);if(body.command==='start'){const offset=t.phase==='Break'?1500+(300-t.remaining):1500-t.remaining;r.timer={running:true,started:Date.now()-offset*1000};}else if(body.command==='pause')r.timer={running:false,remaining:t.remaining,phase:t.phase};else if(body.command==='reset')r.timer={running:false,remaining:1500,phase:'Focus'};else throw new AIError('Invalid timer command.',400);}
 else if(action==='goal'){if(user.id!==r.owner)throw new AIError('The room owner updates shared progress.',403);r.completed=Math.min(r.target,Math.max(0,r.completed+(body.delta===-1?-1:1)));}
 else if(action==='quiz'){if(user.id!==r.owner)throw new AIError('The room owner starts quiz rounds.',403);if(r.quiz&&!r.quiz.closed)throw new AIError('Reveal the current round before starting another.',409);const topic=body.topic;if(!catalog[topic])throw new AIError('Choose a built-in quiz topic.',400);const q=catalog[topic].questions[r.quizIndex++%catalog[topic].questions.length];r.quiz={id:id(),topic,question:q[0],options:q[1],correct:q[2],explanation:q[3],answers:{},closed:false};}
 else if(action==='answer'){const q=r.quiz;if(!q||q.id!==body.quiz||q.closed)throw new AIError('This round has ended.',409);if(q.answers[user.id])throw new AIError('You already answered this round.',409);if(!Number.isInteger(body.answer)||body.answer<0||body.answer>=q.options.length)throw new AIError('Choose an answer.',400);const correct=body.answer===q.correct;q.answers[user.id]={choice:body.answer};const s=r.scores[user.id]??={points:0,correct:0,attempts:0,weak:{}};s.attempts++;s.points+=correct?10:0;s.correct+=correct?1:0;if(!correct)s.weak[q.topic]=(s.weak[q.topic]||0)+1;}
 else if(action==='reveal'){if(user.id!==r.owner)throw new AIError('Only the owner can end the round.',403);if(r.quiz)r.quiz.closed=true;}
 else if(action==='ai'){checkLimit(user.id,'ai',10);const question=text(body.text,3000);const context=r.messages.slice(-15).map(m=>`${m.name}: ${m.text}`).join('\n');const response=await ai([{role:'user',text:`Room topic: ${r.topic}\nShared goal: ${r.goal}\nGroup discussion:\n${context}\nRequest: ${question}`}],{mode:body.mode});if(!db.data.rooms[r.id])throw new AIError('Room was closed.',404);r.messages.push({id:id(),name:'MindMate AI',text:response,at:Date.now(),ai:true});}
 else if(action==='leave'){r.members=r.members.filter(uid=>uid!==user.id);user.rooms=user.rooms.filter(rid=>rid!==r.id);if(!r.members.length)delete db.data.rooms[r.id];else if(r.owner===user.id)r.owner=r.members[0];db.save();return json(200,{ok:true});}
 else throw new AIError('Unknown room action.',404);db.save();return json(200,{room:roomView(r,user)});}
 if(path==='/api/export'&&req.method==='GET')return json(200,{profile:user.profile,rooms:user.rooms.map(r=>db.data.rooms[r]).filter(Boolean).map(r=>({name:r.name,notes:r.notes,messages:r.messages.filter(m=>m.user===user.id)}))});
 if(path==='/api/delete'&&req.method==='POST'){for(const r of Object.values(db.data.rooms)){r.members=r.members.filter(uid=>uid!==user.id);r.messages=r.messages.filter(m=>m.user!==user.id);delete r.scores[user.id];if(r.quiz)delete r.quiz.answers[user.id];if(!r.members.length)delete db.data.rooms[r.id];else if(r.owner===user.id)r.owner=r.members[0];}delete db.data.users[user.id];for(const u of Object.values(db.data.users))u.invitations=u.invitations.filter(i=>db.data.rooms[i.room]);db.save();res.setHeader('Set-Cookie','mm_session=; HttpOnly; SameSite=Strict; Path=/; Max-Age=0');return json(200,{ok:true});}
 if(['/api/chat','/api/image'].includes(path)&&req.method==='POST'){checkLimit(user.id,'ai',10);if(path==='/api/image'){if(typeof body.image!=='string'||!/^data:image\/(png|jpeg|webp);base64,[A-Za-z0-9+/=]+$/.test(body.image))throw new AIError('Use a JPG, PNG or WebP image.',400);return json(200,{text:await ai([],{image:body.image})});}if(!Array.isArray(body.messages)||!body.messages.length||body.messages.length>150||body.messages.some(m=>!['user','assistant'].includes(m.role)||typeof m.text!=='string'||m.text.length>20000))throw new AIError('Invalid conversation.',400);return json(200,{text:await ai(body.messages,{mode:body.mode})});}
 throw new AIError('Not found.',404);
 }catch(e){json(e.status||500,{error:e instanceof AIError?e.message:'Could not complete the request. Please retry.'});}
});
server.listen(port,host,()=>console.log(`MindMate AI running at ${origin}`));
